### ISSUE TITLE
用户信息导出-后缀格式问题

### ISSUE THREAD

**Issue by xuming-wang** [jeecgboot/ant-design-vue-jeecg#12]
##### 前端版本：vue3版？还是 vue2版？
vue2版

##### 问题描述：
使用管理员账户导出用户信息，结果导出为doc文件,应该导出为Excel文件

##### 截图&代码：
![image](https://user-images.githubusercontent.com/38493982/219258765-feb340e2-b1d8-4d92-a0bc-c5aa00051fe5.png)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 针对问题请说明是Online在线功能(需说明用的主题模板)，还是生成的代码功能；

**Comment by zhangdaiscott** [comment]
sq

**Comment by lsqGitHub716** [comment]
测试vue2线上用户管理导出Excel文件正常，请确认一下你本地的具体问题原因
![image](https://user-images.githubusercontent.com/65587928/230850011-aef8349f-7893-4fc7-8611-0829175baebb.png)
