### ISSUE TITLE
普通用户授权菜单后，登录后，404

### ISSUE THREAD

**Issue by mygeorge** [jeecgboot/ant-design-vue-jeecg#20]

**Comment by mygeorge** [comment]
![5352600634_101047639462_FEBAA290-818B-4c7a-AC8E-C7A0BAEE932E](https://user-images.githubusercontent.com/52056350/230285657-5bbc5b1d-05fa-440c-8583-9903089d6c5f.png)

**Comment by mygeorge** [comment]
这个是普通用户登录的时候，创建完成角色，然后登录【普通用户账号】，然后就报404，刷新后就没有问题了

**Comment by mygeorge** [comment]
版本是3.4.3last

**Comment by zhangdaiscott** [comment]
应该是记忆跳转的地址没有权限

**Comment by mygeorge** [comment]
![image](https://user-images.githubusercontent.com/52056350/230287079-03a88e37-c7c5-41e0-ad9e-684a0112434e.png)

**Comment by mygeorge** [comment]
![864b952344e500b2897f2d215d31daf](https://user-images.githubusercontent.com/52056350/230287118-1501ebb8-92cc-4903-aec8-5f859fb1470e.png)

**Comment by mygeorge** [comment]
![721b45fa23ac95ac15a5e6fbb2d063d](https://user-images.githubusercontent.com/52056350/230287157-7c8f6d29-91c9-4bd0-896c-6e758f95ca90.png)

**Comment by mygeorge** [comment]
如何解决？ 有没有解决方案，感谢大佬

**Comment by mygeorge** [comment]
我登录后的地址是首页，可是首页我配置权限了呀

**Comment by mygeorge** [comment]
![image](https://user-images.githubusercontent.com/52056350/230287635-0b310228-1b55-423e-819e-ec12ff50fa46.png)

**Comment by mygeorge** [comment]
/sys/permission/getUserPermissionByToken?_t=1680761578

**Comment by zhangdaiscott** [comment]
录个视频

**Comment by mygeorge** [comment]
好的，感谢官方

**Comment by mygeorge** [comment]
https://user-images.githubusercontent.com/52056350/230288622-ad6735b4-b572-4282-ba4b-860d0798443a.mp4

**Comment by mygeorge** [comment]
官方大大，如何解决呀，感谢

**Comment by zhangdaiscott** [comment]
sq

**Comment by mygeorge** [comment]
什么东西？
