### ISSUE TITLE
请问vue2版本还维护吗， 以后还会支持后台3.5.0+的版本吗

### ISSUE THREAD

**Issue by wuchangrong** [jeecgboot/ant-design-vue-jeecg#24]
##### 版本号：
3.4.4

##### 问题描述：
 请问vue2版本还维护吗， 以后还会支持后台3.5.0+的版本吗

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
会，节奏会慢一些
