### ISSUE TITLE
vue2版本不更新了吗

### ISSUE THREAD

**Issue by wuchangrong** [jeecgboot/ant-design-vue-jeecg#30]
##### 版本号：
2.4.3

##### 问题描述：
vue2版本以后还更新吗， 多久更新一次？

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
更新，频率降低
