### ISSUE TITLE
如何集成最新的仪表盘

### ISSUE THREAD

**Issue by sunjie798893816** [jeecgboot/ant-design-vue-jeecg#31]
#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
jeecgboot 手工升级集成仪表盘步骤，参考这两个提交
https://github.com/jeecgboot/jeecg-boot/commit/cecbc3f62825cb0af30ccfd29453f0f01b648867
https://github.com/jeecgboot/jeecgboot-vue3/commit/7f03885154d0b2706fc8048f68fe13c603201d67

**Comment by zhangdaiscott** [comment]
仪表盘是vue3的，vue2前端集成不了
