### ISSUE TITLE
请问点击某个菜单，如何在一个新的标签页中显示信息？类似于“大屏设计器”的实现

### ISSUE THREAD

**Issue by yuzy0208** [jeecgboot/ant-design-vue-jeecg#35]
##### 版本号：
3.4.3

##### 问题描述：
我想要实现一个类似于“大屏设计器”的功能，点击菜单之后，创建一个新的标签页，显示信息，请问如何实现？谢谢

##### 截图&代码：
![image](https://github.com/jeecgboot/ant-design-vue-jeecg/assets/140529440/2807a219-48df-4820-bbda-c7f312b5092e)

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
你看下大屏菜单是怎么配置的，不就知道了，或者看看文档
