### ISSUE TITLE
服务器访问后端404问题

### ISSUE THREAD

**Issue by Durant-Wen** [jeecgboot/ant-design-vue-jeecg#47]
##### 截图&代码：
index.html配置：
<img width="820" alt="image" src="https://github.com/jeecgboot/ant-design-vue-jeecg/assets/46209098/dc05bbcf-eb06-4651-adce-2927ede22a85">

前端页面调试窗口：
<img width="1213" alt="image" src="https://github.com/jeecgboot/ant-design-vue-jeecg/assets/46209098/d4b04311-f6a0-47bd-b29e-85716b22c42c">

#### 友情提示（为了提高issue处理效率）：
  - 未按格式要求发帖，会被直接删掉;
  - 请自己初判问题描述是否清楚，是否方便我们调查处理；
  - 描述过于简单或模糊，导致无法处理的，会被直接删掉；

**Comment by zhangdaiscott** [comment]
应该是你后台接口配置有问题
